# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
locale                   : "en-US"
title                    : "Fuzail Palnak"
title_separator          : "-"
name                     : 
description              : 
url                      : https://fuzailpalnak.github.io # the base hostname & protocol
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "fuzailpalnak/fuzailpalnak.github.io"

# SEO Related
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# Social Sharing
twitter:
  username               : &twitter
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 :  # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles


# Analytics
analytics:
  provider               : "google-universal"
  google:
    tracking_id          : "UA-158202605-1"


# Site Author
author:
  name             : 
  avatar           : "profile.png"
  bio              : "Software Engineer and Computer Vision Enthusiast"
  location         : 
  maplocation      : https://www.google.com/maps/place/Graz
  employer         :
  pubmed           : 
  googlescholar    : "https://scholar.google.com/citations?user=xTmdJ_MAAAAJ&hl=en"
  email            :
  researchgate     :
  dblp             :

  uri              :
  github           : "fuzailpalnak"
  impactstory      : #"https://profiles.impactstory.org/u/xxxx-xxxx-xxxx-xxxx"
  linkedin         : "fuzail-palnak-b4962994"
  orcid            :
  semanticscholar  :
  stackoverflow    : "https://stackoverflow.com/users/7984359/thefifthjack005"
  steam            :
  twitter          : 
  xing             :
  youtube          :
  reddit           :
  wikipedia        :
  vimeo            :


# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - python/*
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Collections
collections:
  - pubs
  - pubs_workshops
  - theses
  - downloads
  #publications:
  #  output: false
  #  permalink: /:collection/:path/
  #portfolio:
  #  output: true
  #  permalink: /:collection/:path/
  

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _publications
  #- scope:
  #    path: ""
  #    type: publications
  #  values:
  #    layout: single
  #    author_profile: true
  #    share: false
  #    comments: false
  # _portfolio
  #- scope:
  #    path: ""
  #    type: portfolio
  #  values:
  #    layout: single
  #    author_profile: true
  #    share: false
  #    comment: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
timezone: Europe/Vienna # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins
plugins:
  #- jekyll-paginate
  #- jekyll-sitemap
  #- jekyll-gist
  #- jekyll-feed
  - jekyll-redirect-from
# mimic GitHub Pages with --safe
#whitelist:
  #- jekyll-paginate
  #- jekyll-sitemap
  #- jekyll-gist
  #- jekyll-feed
 # - jemoji



# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
