# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
locale                   : "de-AT"
title                    : "Horst Possegger"
title_separator          : "-"
name                     : 
description              : 
url                      : https://snototter.github.io # the base hostname & protocol
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "snototter/snototter.github.io"

# SEO Related
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# Social Sharing
twitter:
  username               : &twitter
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 :  # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles


# Analytics
analytics:
  provider               :  "google-universal" # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : "UA-183955667-1"


# Site Author
author:
  name             : 
  avatar           : "brick.jpg"
  bio              : "Computer Vision by profession, Tinkering by passion"
  location         : 
  maplocation      : https://www.google.com/maps/place/Graz
  employer         :
  pubmed           : 
  googlescholar    : "https://scholar.google.com/citations?user=iWPrl3wAAAAJ&hl=en"
  email            :
  researchgate     : "https://www.researchgate.net/profile/Horst_Possegger"
  dblp             : "https://dblp.uni-trier.de/pid/135/4917.html"

  uri              :
  github           : "snototter"
  impactstory      : #"https://profiles.impactstory.org/u/xxxx-xxxx-xxxx-xxxx"
  linkedin         : "horst-possegger-818b80b9"
  orcid            : "https://orcid.org/0000-0002-5427-9938"
  semanticscholar  : "https://www.semanticscholar.org/author/Horst-Possegger/1720811"
  stackoverflow    :
  steam            :
  twitter          : 
  xing             :
  youtube          : "ldw"
  reddit           : "https://www.reddit.com/user/sarcastic-snot-otter"
  wikipedia        :
  vimeo            : "https://vimeo.com/snototter"


# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Collections
collections:
  publications:
    output: false
    permalink: /:collection/:path/
  #portfolio:
  #  output: true
  #  permalink: /:collection/:path/
  

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: false
      comments: false
  # _portfolio
  #- scope:
  #    path: ""
  #    type: portfolio
  #  values:
  #    layout: single
  #    author_profile: true
  #    share: false
  #    comment: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
timezone: Europe/Vienna # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins
plugins:
  #- jekyll-paginate
  #- jekyll-sitemap
  #- jekyll-gist
  #- jekyll-feed
  - jekyll-redirect-from
# mimic GitHub Pages with --safe
#whitelist:
  #- jekyll-paginate
  #- jekyll-sitemap
  #- jekyll-gist
  #- jekyll-feed
 # - jemoji



# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
